baseURL = "https://jarvenp.fi"
languageCode = "fi"
title = "Matias Järvenpää"
DefaultContentLanguage = "fi"
[languages]
  [languages.fi]
    weight = 1
    contentDir = "content/fi"
    [languages.fi.params]
      readMore = "Lue lisää..."
      projects = "Projekteja"
      back = "Takaisin"
      quote = "Tuntuu siltä, että jokaisen tänne kirjoittamani tekstin viimeisen kappaleen aihe on, että häpeän projektiani, mutta olen silti tyytyväinen siihen, että se toimii."
  [languages.en]
  	contentDir = "content/en"
    weight = 2
    [languages.en.params]
      readMore = "Read more..."
      projects = "Projects"
      back = "Back to main page"
      quote = "I feel like every text I write here ends with me saying that I'm ashamed of the project but I'm still happy that it works."
